export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';

export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';