export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';

export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';
export const RESET_ROOM = 'RESET_ROOM';

export const FIND_ROOMS_START = 'FIND_ROOMS_START';
export const FIND_ROOMS_SUCCESS = 'FIND_ROOMS_SUCCESS';
export const FIND_ROOMS_FAILED = 'FIND_ROOMS_FAILED';
export const UPDATE_ROOM = 'UPDATE_ROOM';

export const LOAD_ROOM_START = 'LOAD_ROOM_START';
export const LOAD_ROOM_SUCCESS = 'LOAD_ROOM_SUCCESS';
export const LOAD_ROOM_FAILED = 'LOAD_ROOM_FAILED';
