export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';

export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';
export const RESET_ROOM = 'RESET_ROOM';

export const FIND_ROOMS_START = 'FIND_ROOMS_START';
export const FIND_ROOMS_SUCCESS = 'FIND_ROOMS_SUCCESS';
export const FIND_ROOMS_FAILED = 'FIND_ROOMS_FAILED';
export const UPDATE_ROOM = 'UPDATE_ROOM';

export const LOAD_ROOM_START = 'LOAD_ROOM_START';
export const LOAD_ROOM_SUCCESS = 'LOAD_ROOM_SUCCESS';
export const LOAD_ROOM_FAILED = 'LOAD_ROOM_FAILED';
export const UPDTAE_ROOM = 'UPDATE_ROOM';

export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';
export const UPDATE_USERS = 'UPDATE_USERS';
export const RESET = 'RESET';

export const TOGGLE_FRIEND_START = 'TOGGLE_FRIEND_START';
export const TOGGLE_FRIEND_SUCCESS = 'TOGGLE_FRIEND_SUCCESS';
export const TOGGLE_FRIEND_FAILED = 'TOGGLE_FRIEND_FAILED';

export const ADD_MESSAGES_USERS = 'ADD_MESSAGES_USERS';
export const ADD_USER = 'ADD_USER';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const EDIT_AVATAR_START = 'EDIT_AVATAR_START';
export const EDIT_AVATAR_FAILED = 'EDIT_AVATAR_FAILED';
export const EDIT_AVATAR_SUCCESS = 'EDIT_AVATAR_SUCCESS';
export const ADD_AVATAR_SUCCESS = 'ADD_AVATAR_SUCCESS';
export const DELETE_AVATAR_SUCCESS = 'DELETE_AVATAR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
